development: &default
  adapter: postgresql
  database: maintenance-scheddo_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: maintenance-scheddo_test
